[plugin-info]
SHORT_PLUGIN_NAME = 'stellarnet'

package-url = 'https://github.com/rgeneaux/pymodaq_plugins_stellarnet'
description = 'Plugin for StellarNet spectrometers'

author = 'Romain Géneaux'
author-email = 'romain.geneaux@cea.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = [pyusb]
